version: '3.8'
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db
    restart: always
    networks:
      - go-echo-rest-api
networks:
  go-echo-rest-api:
